version: '3.8'

services:
  vault:
    build: .
    environment:
      - APP_APPLICATION__HOST=0.0.0.0
      - APP_APPLICATION__PORT=8000
      - APP_APPLICATION__PRIVATE_KEY=LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRRFp6czg2bzhCRkQzTmQKaGpsaWVicXpabGhBalowcVQwaHZJc3JKT1BZM2RIb0IrbDQ2Ukp6WE1BbEdHc1pqQk5LWkJDZXl4R2ZaVFdZeQpRcm9MMWlCWDBPc2V0MnR3TVE4TkYrcUdoOTFUaGFCVXRXaS9xcWphcUFaZFY4azlRUjRwZCs2TldWVTdGUzl1CnJCNEsrWHlnL0QyOTJQTHdRU0taR3B6ZTVReXhnVzFpQWJKNTNBOGt1eUlpdDJOQ0paYTgxYzZjVmU4SmY0eXIKbHBpeEVFdWo1V09GQjlpU2c1czJiS2w0VUxPR3hSY3R2NnMxdUFBUXNpM1J1bFJSWnBKWjdROUJUcDR0OFdwcgo0Z0JFbDc3Z0xwMTZwRWlod3QvTVZIT0lMeCtMV2l6VjR2amswc2FWZnJDR1lmam5XbWxJdStRMmpQaXkvRThoCnRybzVyY3RiQWdNQkFBRUNnZ0VBY1haR2hhbWdFMW5GSTBjMHhaUGNLbkI2TU1hVXhPR2dQaVRGdHFVeHZobXoKSlN5andYN1VwVlNrd0J4YWxHS0N3cXRqY3NEVnlHR0ZoMUV6VWM4dDhoRW5LazBxYnJ0ZnQ5WnBtY05WREpsagp1RHo0WUVBcXpoMFJrN2FUWXBGMWdPeTFISFVZN1RwUUJ6c3FPMVZVRXhqVG9QNVBMOUQra1B0SUZPVUZBOElPCkJkSnk1TjAvL292NWlaeHZsalI1WGJ2dmtyQWZkVHcydlJzZ01JWDJiR05uZnJNR2grbzlDblNJMi9aRzVHQ3oKUXgzTldab2xiOS9mSTU4RzJaT1V4cGUxb3QvaWRDOCtDOTdXamxRMTVmWmtHQXNxbWxsZzI4QkptS3puVElpMgpoSGpmTkpEdEJORjNYb0FDQXJob1pRS3M1c1lFMGZvMTZFcUl4U2x0SVFLQmdRRDhUaXZjbU1BYnEyeURqRk9MCkcxTmhzQS9XNlBlOEVNeG0wWjUzNGVSWDBhWUFqVDVFNjFhcmZpOEkvS1lkOXVCSnF4SEUyU1NpUTFKY2lUTWsKWTFkSVVpWTRsQTV0UFRIVGlTbkQzMFVzQWRKbWJjbnEzbDUzbTdYcDNlQXZCcGtvYWJzRlN4L1FnZUdrZzB4bQo3cXVLNVJYMzdwWXpMVjVIeEJrbi8zZ21Id0tCZ1FEYy8xRFdDTklDVW80T2RDYmpJOExpS05hTFp2SDIwck1lCk9SakFoOXdHbzlVOCtzU1dxUTgwZmJYWk9tK0JIYjAybE5GWmRCLzB4eERTQWNrZ05WNFluUjBvOWhoWlY0NDcKZUZxVGRjVENlNlczRzJBdUpyUDFHQXVsZG00RGZud3dGY2NLL0NzNTBmOWxkRy9SbVRrOUFwZ1Uwb1BXU2VmKwp4TU1WL25IYlJRS0JnQ3lrZUVaVUVNblVqeUxIbFpDcmlSbGoyYW1oRnhTRHRHY00rQWttUXd6MjMzU0JpVjhRCmRRbHJEazk4eExmUWt1YjJDZkxXcVJDODhMbkczUEczVWg1TnlzMkFCUDEzTW5YSGMwaGhIUkFvVWw0bFZ2RGoKMzdzeUpnSDNiRTlsejN2REdZQmFSb3JTTUdhM2hMRkIwY0NGd0ZsYU1lRmtTYVpSSUZKZmRaYnBBb0dBV1pBZgpjcDZnZmRCM1FlUlEzanpmL2tnT3F2Qk5uM3BFblRzR2pRQ0NheTU2ZlB3a0wrclQvckh6d05XdDJ1WHlpT3hHCjY3bmtPWTl6Z2FpM21oWUd6SExnSG5tZDVKZFhUVUs1Y29tSDlFbW9IMDA0N1h0QjgxS0xaY05aVXBFd1EweVEKSGlPVVlScDZKdVBKYldocmlnNURGQzA4d051eTZjMVVRdFdiendFQ2dZQUZRaDU4VTVvS2VSZW92NWJJR0NDcwpzUzJRVndwWnZUSWNubE1VbDZicTVSZzBQSEZiLzlpMlR5dlVJQ2pxYlVPQ1RPN0QwWTFnS3JxK1F1NDU1MWFiCndWR09sZ0h1eUd4ZjF2cHZHZURQRnJjdDNrbUoxWUlVTmw0QVZmRTQwZkp2ZHIwNDdkMk9HOTUzZ2txK1ZaSmQKREk0ZitpTFlDdDF6SVV4SGoybUZ5dz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
      - APP_APPLICATION__PUBLIC_KEY=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEyYzdQT3FQQVJROXpYWVk1WW5tNgpzMlpZUUkyZEtrOUlieUxLeVRqMk4zUjZBZnBlT2tTYzF6QUpSaHJHWXdUU21RUW5zc1JuMlUxbU1rSzZDOVlnClY5RHJIcmRyY0RFUERSZnFob2ZkVTRXZ1ZMVm92NnFvMnFnR1hWZkpQVUVlS1hmdWpWbFZPeFV2YnF3ZUN2bDgKb1B3OXZkank4RUVpbVJxYzN1VU1zWUZ0WWdHeWVkd1BKTHNpSXJkalFpV1d2TlhPbkZYdkNYK01xNWFZc1JCTApvK1ZqaFFmWWtvT2JObXlwZUZDemhzVVhMYityTmJnQUVMSXQwYnBVVVdhU1dlMFBRVTZlTGZGcWErSUFSSmUrCjRDNmRlcVJJb2NMZnpGUnppQzhmaTFvczFlTDQ1TkxHbFg2d2htSDQ1MXBwU0x2a05vejRzdnhQSWJhNk9hM0wKV3dJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
      - APP_APPLICATION__BASE_URL=http://localhost:8000
      - APP_DATABASE__URL=postgres://postgres:password@postgres_db:5432/vault
      - APP_REDIS__URL=redis://default:password@redis:6379
      - APP_STORAGE__DRIVER=s3
      - APP_STORAGE__REGION=auto
      - APP_STORAGE__ENDPOINT=http://minio:9000
      - APP_STORAGE__BUCKET_NAME=testing_data
      - APP_STORAGE__ACCESS_KEY_ID=minioadmin
      - APP_STORAGE__SECRET_KEY=minioadmin
      - APP_ADMIN__EMAIL=admin@valink.io
      - APP_ADMIN__PASSWORD=vault-admin
      - APP_ADMIN__CLIENT_ID=1c5d66ea-0b0e-42a0-b57d-757da66f282f
      - APP_ADMIN__CLIENT_SECRET=1af64f63cf18a69dbf0bf3ce3a2698118646ec1e
    ports:
      - '8000:8000'
    depends_on:
      - postgres_db
      - redis
      - minio

  redis:
    image: redis:latest
    command: redis-server --requirepass password
    ports:
      - '6379:6379'

  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vault
    ports:
      - '5432:5432'

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - /var/data/vault-minio:/data
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"
